### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by Webbah** [upb-lea/dare#26]
### Create a logger
 - which collects all the warnings and infos of the env and nodeconstrutor
 - based on `verbose` logs/tells(?) from all (e.g. 2) to nothing (0)

**Comment by janstenner** [comment]
The logging system is now integrated in develop

**Comment by janstenner** [comment]
If you want to log a message you can simply use the following commands

`@debug "This is a debug level log"

@info "This is info level"

@warn "This is a warning"

@error "This is an error"`

**Comment by Webbah** [comment]
Functionality implemented, pls use instead of print to command line
